name: stardewmods
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_manager: ^0.0.2
  google_fonts: ^6.3.3
  flutter_inappwebview: ^6.1.5
  html: ^0.15.6
  bitsdojo_window: ^0.1.6
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  archive: ^4.0.7
  delightful_toast: ^1.1.0
  shared_preferences: ^2.5.4
  clipboard: ^3.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/fonts/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/image/logo.png"
    icon_size: 256